# Generated by Django 3.0.2 on 2020-05-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200503_1744'),
        ('accounts', '0003_auto_20200502_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.ManyToManyField(to='shop.Item'),
        ),
    ]
