# Generated by Django 3.0.7 on 2020-06-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200615_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='name_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='reviews_list_private',
            field=models.BooleanField(default=False),
        ),
    ]
