# Generated by Django 3.0.7 on 2020-06-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200615_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name_private',
            new_name='full_name_private',
        ),
    ]
