# Generated by Django 3.0.7 on 2020-06-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200620_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook_private',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram_private',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter_private',
        ),
    ]
