# Generated by Django 3.0.4 on 2020-07-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='accounts/profile_pics/def.png', upload_to='accounts/profile_pics'),
        ),
    ]
