# Generated by Django 3.0.2 on 2020-05-02 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_auto_20200502_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(1, '&#11088;'), (2, '&#11088;&#11088;'), (3, '&#11088;&#11088;&#11088;'), (4, '&#11088;&#11088;&#11088;&#11088;'), (5, '&#11088;&#11088;&#11088;&#11088;&#11088;')], default=5),
        ),
    ]
