# Generated by Django 3.0.2 on 2020-05-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars_rendered',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
