# Generated by Django 3.0.2 on 2020-05-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200503_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='stars_rendered',
        ),
    ]
