# Generated by Django 3.0.2 on 2020-05-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
