# Generated by Django 3.0.4 on 2020-07-31 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20200702_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='shop/item_imgs/def.png', upload_to='shop/item_imgs'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='order_stack_set', through='shop.OrderStack', to='shop.Item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('on_del', 'On Delivery'), ('paypal', 'PayPal'), ('ccard', 'CreditCard')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment_option',
            field=models.CharField(choices=[('post', 'Post'), ('dpd', 'DPD'), ('ppl', 'PPL')], max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('items', models.ManyToManyField(to='shop.Item')),
            ],
        ),
    ]
